In [79]:
%matplotlib inline
import random
import torch

In [80]:
def synthetic_data(w,b,num_examples):
    X=torch.normal(0,1,(num_examples,len(w)))
    y=X*w+b
    y+=torch.normal(0,0.01,y.shape)
    return X,y.reshape((-1,1))

true_w=torch.tensor([2,-3.4])
true_b=4.2
X,y=synthetic_data(true_w,true_b,1000)

In [81]:
from torch.utils.data import DataLoader,Dataset

In [82]:
class myData(Dataset):
    def __init__(self,X,y):
        self.X=X
        self.y=y
    def __getitem__(self,idx):
        return self.X[idx],self.y[idx]
    def __len__(self):
        return len(self.X)
data=myData(X,y)
batch_size=10
loader=DataLoader(data,batch_size=batch_size,shuffle=True)

In [83]:
for X,y in loader:
    print(X,y)

tensor([[-0.3456,  0.2882],
        [ 0.3768, -1.0664],
        [-0.1112, -0.5688],
        [-0.8666,  0.6929],
        [-0.1647, -0.3080],
        [ 1.5900, -0.0308],
        [ 0.7094,  0.8488],
        [ 0.6458, -0.0491],
        [-1.2811,  0.7791],
        [ 0.5473,  0.0151]]) tensor([[1.4096],
        [2.2130],
        [3.4697],
        [4.2351],
        [4.9393],
        [3.5343],
        [3.8762],
        [7.4380],
        [6.9046],
        [9.0340]])
tensor([[ 0.3576, -0.5730],
        [-0.4995,  0.9822],
        [-1.9349,  0.5572],
        [-1.4113, -1.9258],
        [-0.9254,  0.1262],
        [ 0.2757, -0.7497],
        [-0.2678, -0.0154],
        [-0.3021, -2.0882],
        [-0.2939,  0.7955],
        [-1.5927,  0.3971]]) tensor([[ 4.7498],
        [-1.5463],
        [ 0.5295],
        [ 4.1562],
        [ 5.1476],
        [-1.0472],
        [ 4.1346],
        [ 0.9458],
        [ 1.8819],
        [ 8.2350]])
tensor([[ 0.1567, -1.4336],
        [ 0.1223,  1.1406],
        [ 

In [84]:
from torch import nn

In [85]:
net=nn.Sequential(nn.Linear(2,1))

In [86]:
net[0].weight.data.normal_(0,0.)
net[0].bias.data.fill_(0)

tensor([0.])

In [87]:
loss_fn=nn.MSELoss()

In [88]:
optimizer=torch.optim.SGD(net.parameters(),lr=0.01)

In [89]:
num_epoch=20
for epoch in range(num_epoch):
    for X,y in loader:
        loss=loss_fn(net(X),y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

In epoch 0,the loss is 4.3646
In epoch 1,the loss is 6.2797
In epoch 2,the loss is 10.5806
