In [2]:
import tensorflow as tf
import tensorflow.keras as keras

In [3]:
unq_categories=['music','movie','finance','game','military','history']
id_mapping_layer=keras.layers.StringLookup(vocabulary=unq_categories)

In [10]:
emb_layer=keras.layers.Embedding(input_dim=len(unq_categories)+1,output_dim=4)

In [12]:
cate_input=tf.constant(['music','movie','finance','game','military','history','None'],dtype=tf.string)

In [13]:
cate_ids=id_mapping_layer(cate_input)

In [14]:
cate_ids

<tf.Tensor: shape=(7,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 0])>

In [15]:
cate_embeddings=emb_layer(cate_ids)

In [16]:
cate_embeddings

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[ 0.02345724,  0.00665563,  0.01693017, -0.03558536],
       [-0.02148782,  0.04487641, -0.00723404,  0.02100572],
       [ 0.04881147,  0.03616324, -0.04422485, -0.04370501],
       [-0.04590491, -0.00100405, -0.04523338, -0.0300947 ],
       [-0.00692356, -0.01647278,  0.01798001,  0.04414478],
       [ 0.03040325,  0.00555838, -0.03856608,  0.03078673],
       [-0.01715499, -0.03218298,  0.03396611,  0.00218197]],
      dtype=float32)>